### PR TITLE
i think it's ready [enough] ... 😄

### PR DESCRIPTION
**Pull request by colleenmcginnis**
it looks like every file was changed, but that's only because i changed the "work page" folder to just "work"

### CODE REVIEW

**Comment by colleenmcginnis** [comment]
@danswick is this expected or did i mess something up? :disappointed: 

"We can’t automatically merge this pull request.
Use the command line to resolve conflicts before continuing."

**Comment by danswick** [comment]
That usually happens when you have commits on the master branch that occurred after you created the fork. You should be able to open up the conflicting file in a text editor and see something like this: 

image

See this post - https://help.github.com/articles/resolving-merge-conflicts/. 

Basically, you have to go into that conflicting file, pick which change you prefer, save, then commit again. 

You can also force git to pick one or the other through the command line. Check out this article for more details - https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/.

**Comment by danswick** [comment]
Looks like you got it :+1:

**Comment by colleenmcginnis** [comment]
yep! http://media.giphy.com/media/qoZrgON4yNUs0/giphy.gif

thanks for ALL your help!!

**Comment by danswick** [comment]
Niiiiice. Congrats! :shipit:

**Pull request merged**
